### ISSUE TITLE
权重文件格式和代码设置冲突

### ISSUE THREAD

**Issue by fly361** [openmedlab/USFM#10]
你好，我按照您最新提供的权重：USFM_latest.pth，
按照您的微调命令：python usfm/train.py tag=seg_$dataset（已修改） experiment=ftSeg.yaml model.net.backbone.pretrained=assets/USFMpretrained.ckpt data=$dataset data="{batch_size:40, num_workers:4}" 
trainer="{devices:[0,1], strategy:ddp}" 进行了运行，

但是却发生了如下段的错误，我经过分析，猜测这是因为您的权重文件是.pth格式的文件，而您编写的项目是针对.ckpt格式的。
请问是否是这样的呢？
那么，我们该如何进行修改，能正确运行命令，提取权重文件呢？
还有一个小问题，请问运行您的项目，大概需要多大的显存呢？
感谢您做出的贡献，如能百忙之中解惑，不胜感激！

**错误**
[2024-04-26 08:23:06,839][usfm.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/hyzheng/anaconda3/envs/USFM/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/hyzheng/Projects/USFM/USFM-master/usfm/models/beitSegLit.py", line 29, in __init__
    self.net = MODELS.build(dict(OmegaConf.to_container(net)))
  File "/home/hyzheng/anaconda3/envs/USFM/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/hyzheng/anaconda3/envs/USFM/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/hyzheng/anaconda3/envs/USFM/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/hyzheng/anaconda3/envs/USFM/lib/python3.9/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 89, in __init__
    self.backbone = MODELS.build(backbone)
  File "/home/hyzheng/anaconda3/envs/USFM/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/hyzheng/anaconda3/envs/USFM/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/hyzheng/anaconda3/envs/USFM/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/hyzheng/Projects/USFM/USFM-master/usfm/models/components/backbone/beit.py", line 480, in __init__
    self.init_weights(pretrained)
  File "/home/hyzheng/Projects/USFM/USFM-master/usfm/models/components/backbone/beit.py", line 518, in init_weights
    load_checkpoint(self, pretrained, strict=False)
  File "/home/hyzheng/Projects/USFM/USFM-master/usfm/models/components/backbone/beit.py", line 29, in load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/hyzheng/anaconda3/envs/USFM/lib/python3.9/site-packages/torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/hyzheng/anaconda3/envs/USFM/lib/python3.9/site-packages/torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
**RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory**

**Comment by George-Jiao** [comment]
Thanks for the suggestion. The newest version 2.0.0 of USFM has fixed the issue!
